import math
import json
import sys

import pandas as pd

import engine.validate_final_parameters as validation_module
from engine.lammps_interface import EvalResult
from engine.validate_final_parameters import _assess_acceptance


def _config():
    return {
        "targets": {
            "a": {"value": 4.0, "tolerance": 0.1},
            "density": {"value": 1.0, "tolerance": 0.03},
        },
        "validation": {
            "require_tolerances": True,
            "objective_max": 0.03,
            "max_error_percent": 3.0,
        },
    }


def test_acceptance_passes_all_configured_thresholds():
    result = _assess_acceptance(
        _config(),
        objective=0.01,
        properties={"a": 4.05, "density": 1.01},
        percent_errors={"a": 1.25, "density": 1.0},
    )
    assert result["passed"] is True
    assert result["tolerances"]["a"]["passed"] is True


def test_acceptance_reports_each_failed_rule():
    result = _assess_acceptance(
        _config(),
        objective=0.05,
        properties={"a": 4.2, "density": 1.01},
        percent_errors={"a": 5.0, "density": 1.0},
    )
    assert result["passed"] is False
    assert len(result["reasons"]) == 3


def test_acceptance_rejects_missing_or_nonfinite_target_results():
    result = _assess_acceptance(
        _config(),
        objective=math.nan,
        properties={"a": math.nan},
        percent_errors={"a": math.nan},
    )
    assert result["passed"] is False
    joined = " | ".join(result["reasons"])
    assert "missing or non-finite fitted properties: a, density" in joined
    assert "objective nan exceeds" in joined
    assert "missing or non-finite percent errors: a, density" in joined


def test_required_tolerance_must_be_declared():
    config = _config()
    config["targets"]["density"].pop("tolerance")
    result = _assess_acceptance(
        config,
        objective=0.01,
        properties={"a": 4.0, "density": 1.0},
        percent_errors={"a": 0.0, "density": 0.0},
    )
    assert result["passed"] is False
    assert "required target tolerance is not defined: density" in result["reasons"]


def test_validation_exports_complete_resolved_atom_table(tmp_path, monkeypatch):
    config = {
        "atom_types": [{
            "type": 1,
            "label": "C1",
            "params": {"epsilon": 0.1, "sigma": 3.4, "charge": -0.2},
        }],
        "charge": {
            "enabled": True,
            "neutrality_constraint": {"enabled": False, "derive_from_type": None},
        },
        "pair_params": {"mixing_rule": "geometric", "derived_params": []},
        "targets": {
            "density": {
                "value": 1.0,
                "weight": 1.0,
                "unit": "g/cm3",
                "tolerance": 0.03,
            }
        },
        "validation": {
            "property_evaluators": {},
            "property_settings": {},
            "property_units": {"density": "g/cm3"},
            "require_tolerances": True,
            "objective_max": 0.03,
            "max_error_percent": 3.0,
        },
    }

    class FakeRunner:
        def __init__(self, _config):
            pass

        def _resolve_params(self, _params):
            return {"C1_epsilon": 0.1, "C1_sigma": 3.4, "C1_charge": -0.2}

        def evaluate_batch(self, *_args, **_kwargs):
            return [EvalResult(
                params={},
                properties={"density": 1.01},
                objective=0.01,
                success=True,
                per_property_error={"density": 1.0},
            )]

        def _build_pair_coeffs(self, _resolved, directory):
            path = validation_module.Path(directory) / "pair_coeffs.lmp"
            path.write_text(
                "# pair_coeffs.lmp -- generated by FFOpt-LAMMPS\n"
                "# DO NOT EDIT: overwritten before each LAMMPS call\n\n"
                "pair_modify mix geometric\n"
                "pair_coeff 1 1 0.1000000000 3.4000000000\n"
                "set type 1 charge -0.2000000000\n",
                encoding="ascii",
            )
            return str(path)

    output = tmp_path / "validate"
    monkeypatch.setattr(validation_module, "load_config", lambda _: config)
    monkeypatch.setattr(validation_module, "LAMMPSRunner", FakeRunner)
    monkeypatch.setattr(sys, "argv", [
        "validate_final_parameters",
        "--config", str(tmp_path / "runtime.json"),
        "--initial",
        "--output-dir", str(output),
    ])
    validation_module.main()

    atom_table = pd.read_csv(output / "final_atom_parameters.csv")
    assert atom_table.loc[0, "label"] == "C1"
    assert atom_table.loc[0, "charge_e"] == -0.2
    parameter_document = json.loads(
        (output / "final_parameters.json").read_text(encoding="utf-8")
    )
    assert parameter_document["resolved_parameters"]["C1_sigma"] == 3.4
    lammps_text = (output / "final_parameters.lammps").read_text(encoding="ascii")
    assert "include after read_data" in lammps_text
    assert "pair_coeff 1 1" in lammps_text
    assert "set type 1 charge -0.2000000000" in lammps_text
    assert not (output / "pair_coeffs.lmp").exists()
