import sys

import pandas as pd

import engine.finalize_al as finalize_al


def test_finalize_disables_scheduler_pool(tmp_path, monkeypatch):
    audit = tmp_path / "audit"
    audit.mkdir()
    pd.DataFrame([{
        "candidate_id": 1,
        "center_objective": 0.01,
        "objective_mean": 0.011,
        "objective_std": 0.001,
        "objective": 0.012,
        "n_success": 2,
        "n_seeds": 2,
        "A_charge": 0.2,
        "calc_density": 1.1,
        "std_density": 0.01,
    }]).to_csv(audit / "stable_results.csv", index=False)

    config = {
        "atom_types": [{"type": 1, "label": "A"}],
        "targets": {"density": {"value": 1.0, "unit": "g/cm3", "weight": 1.0}},
    }
    observed = {}

    class RecordingRunner:
        def __init__(self, _config, *, start_scheduler_pool):
            observed["start_scheduler_pool"] = start_scheduler_pool

        def _resolve_params(self, raw):
            return {
                "A_epsilon": 0.1,
                "A_sigma": 3.0,
                "A_charge": raw["A_charge"],
            }

        def _build_pair_coeffs(self, _resolved, output_dir):
            path = finalize_al.Path(output_dir) / "pair_coeffs.lmp"
            path.write_text(
                "# pair_coeffs.lmp -- generated by FFOpt-LAMMPS\n"
                "# DO NOT EDIT: overwritten before each LAMMPS call\n",
                encoding="ascii",
            )
            return str(path)

    monkeypatch.setattr(finalize_al, "load_config", lambda _path: config)
    monkeypatch.setattr(finalize_al, "LAMMPSRunner", RecordingRunner)
    monkeypatch.setattr(
        finalize_al,
        "build_parameter_space",
        lambda _config: [("A_charge", -1.0, 1.0)],
    )
    output = tmp_path / "finalize"
    monkeypatch.setattr(sys, "argv", [
        "finalize_al",
        "--config", str(tmp_path / "runtime.json"),
        "--audit", str(audit),
        "--output-dir", str(output),
    ])

    finalize_al.main()

    assert observed["start_scheduler_pool"] is False
    assert (output / "final_summary.json").exists()
    assert (output / "final_parameters.lammps").exists()
